backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  root 'pages#home'

  use_doorkeeper
  devise_for :users
  resources :books

  draw :api
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

backend/app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
end

backend/app/controllers/api/v1/android/books_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Android
      class BooksController < ApiController
        include ApplicationHelper
        before_action :set_book, only: %i[show]
        before_action :is_admin?

        # GET /books or /books.json
        def index
          @books = Book.all
          render json: @books
        end

        # GET /books/1 or /books/1.json
        def show
          render json: @book
        end

        private

        # Use callbacks to share common setup or constraints between actions.
        def set_book
          @book = Book.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def book_params
          params.require(:book)
        end
      end
    end
  end
end

backend/app/controllers/api/v1/books_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BooksController < ApiController
      before_action :set_book, only: %i[show edit update destroy]

      # GET /books or /books.json
      def index
        @books = Book.all
        render json: @books
      end

      # GET /books/1 or /books/1.json
      def show
        render json: @book
      end

      # GET /books/new
      def new
        render json: @book = Book.new
      end

      # GET /books/1/edit
      def edit
        render json: @book
      end

      # POST /books or /books.json
      def create
        @book = Book.new(book_params)

        respond_to do |format|
          if @book.save
            format.html { redirect_to api_v1_book_url(@book), notice: 'Book was successfully created.' }
            format.json { render :show, status: :created, location: @book }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /books/1 or /books/1.json
      def update
        respond_to do |format|
          if @book.update(book_params)
            format.html { redirect_to api_v1_book_url(@book), notice: 'Book was successfully updated.' }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /books/1 or /books/1.json
      def destroy
        @book.destroy

        respond_to do |format|
          format.html { redirect_to api_v1_books_url, notice: 'Book was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = Book.find_by_id(params[:id])
        render json: { error: 'Book not found' }, status: :not_found if @book.nil?
      end

      # Only allow a list of trusted parameters through.
      def book_params
        params.require(:book).permit(:title, :body)
      end
    end
  end
end

backend/app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  include ApplicationHelper
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :is_admin?
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

backend/app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

backend/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= book.body %>
  </p>

</div>

backend/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

backend/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Books</h1>
<h2>
  <%= "#{current_user.email}"%>
</h2>
<h3><%= "Role: #{current_user.role}" %></h3>
<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>
<%= link_to "New book", new_book_path %>

backend/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

backend/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>